import type { PublicApiOperationContract } from "./common.js";
import type { PublicApiSharedTypeName } from "./types.js";

type TypedPublicApiOperationContract =
  PublicApiOperationContract<PublicApiSharedTypeName>;

export const PUBLIC_API_LIVE_OPERATIONS = [
  {
    operationId: "getHealth",
    method: "GET",
    path: "/api/v1/health",
    auth: "public",
    responseEnvelope: "SuccessObject",
    responseTypeName: "PublicHealthPayload",
  },
  {
    operationId: "createContactRequest",
    method: "POST",
    path: "/api/v1/public/contact-requests",
    auth: "public",
    requestTypeName: "ContactRequestSubmission",
    requestBodyRequired: true,
    responseEnvelope: "SuccessObject",
    responseTypeName: "ContactRequestReceipt",
  },
  {
    operationId: "getLiveDashboardSummary",
    method: "GET",
    path: "/api/v1/live/dashboard/summary",
    auth: "bearer",
    responseEnvelope: "SuccessObject",
    responseTypeName: "DashboardSummary",
  },
  {
    operationId: "listLiveForecastRuns",
    method: "GET",
    path: "/api/v1/live/forecasts",
    auth: "bearer",
    responseEnvelope: "SuccessArray",
    responseTypeName: "ForecastRunSummary",
  },
  {
    operationId: "listLatestDailyForecasts",
    method: "GET",
    path: "/api/v1/live/forecasts/latest/daily",
    auth: "bearer",
    responseEnvelope: "SuccessArray",
    responseTypeName: "LatestDailyForecastRow",
  },
  {
    operationId: "getLiveDecisionConfig",
    method: "GET",
    path: "/api/v1/live/decision-config",
    auth: "bearer",
    responseEnvelope: "SuccessObject",
    responseTypeName: "ResolvedDecisionConfigView",
  },
  {
    operationId: "getLiveGoldSchema",
    method: "GET",
    path: "/api/v1/live/gold/schema",
    auth: "bearer",
    responseEnvelope: "SuccessObject",
    responseTypeName: "GoldSchemaView",
  },
  {
    operationId: "listLiveGoldRows",
    method: "GET",
    path: "/api/v1/live/gold/rows",
    auth: "bearer",
    responseEnvelope: "PaginatedSuccess",
    responseTypeName: "CanonicalRecord",
  },
  {
    operationId: "getLiveGoldCoverage",
    method: "GET",
    path: "/api/v1/live/gold/coverage",
    auth: "bearer",
    responseEnvelope: "SuccessObject",
    responseTypeName: "GoldCoverageView",
  },
  {
    operationId: "getLiveGoldProvenance",
    method: "GET",
    path: "/api/v1/live/gold/provenance",
    auth: "bearer",
    responseEnvelope: "SuccessObject",
    responseTypeName: "GoldProvenanceView",
  },
  {
    operationId: "listLiveProof",
    method: "GET",
    path: "/api/v1/live/proof",
    auth: "bearer",
    responseEnvelope: "SuccessArray",
    responseTypeName: "ProofPack",
  },
  {
    operationId: "listLiveCanonicalRows",
    method: "GET",
    path: "/api/v1/live/canonical",
    auth: "bearer",
    responseEnvelope: "PaginatedSuccess",
    responseTypeName: "CanonicalRecord",
  },
  {
    operationId: "getLiveCanonicalQuality",
    method: "GET",
    path: "/api/v1/live/canonical/quality",
    auth: "bearer",
    responseEnvelope: "SuccessObject",
    responseTypeName: "CanonicalQualityDashboard",
  },
  {
    operationId: "listLiveCoverageAlerts",
    method: "GET",
    path: "/api/v1/live/coverage-alerts",
    auth: "bearer",
    responseEnvelope: "SuccessArray",
    responseTypeName: "CoverageAlert",
  },
  {
    operationId: "getLiveCoverageAlertQueue",
    method: "GET",
    path: "/api/v1/live/coverage-alerts/queue",
    auth: "bearer",
    responseEnvelope: "SuccessArray",
    responseTypeName: "DecisionQueueItem",
  },
  {
    operationId: "getLiveScenarioForAlert",
    method: "GET",
    path: "/api/v1/live/scenarios/alert/{alertId}",
    auth: "bearer",
    responseEnvelope: "SuccessObject",
    responseTypeName: "ParetoFrontierResponse",
  },
  {
    operationId: "getLiveDecisionWorkspace",
    method: "GET",
    path: "/api/v1/live/decision-workspace/{alertId}",
    auth: "bearer",
    responseEnvelope: "SuccessObject",
    responseTypeName: "DecisionWorkspace",
  },
  {
    operationId: "generateScenarioForAlert",
    method: "POST",
    path: "/api/v1/scenarios/generate/{alertId}",
    auth: "bearer",
    requestTypeName: "ScenarioGenerationRequest",
    responseEnvelope: "SuccessObject",
    responseTypeName: "ParetoFrontierResponse",
  },
] as const satisfies readonly TypedPublicApiOperationContract[];
