import type { PublicApiOperationContract } from "./common.js";
import type { PublicApiSharedTypeName } from "./types.js";

type TypedPublicApiOperationContract =
  PublicApiOperationContract<PublicApiSharedTypeName>;

export const PUBLIC_API_BUSINESS_OPERATIONS = [
  {
    operationId: "getOrganizationMe",
    method: "GET",
    path: "/api/v1/organizations/me",
    auth: "bearer",
    responseEnvelope: "SuccessObject",
    responseTypeName: "OrganizationProfile",
  },
  {
    operationId: "listDepartments",
    method: "GET",
    path: "/api/v1/departments",
    auth: "bearer",
    responseEnvelope: "SuccessArray",
    responseTypeName: "DepartmentSummary",
  },
  {
    operationId: "listSites",
    method: "GET",
    path: "/api/v1/sites",
    auth: "bearer",
    responseEnvelope: "SuccessArray",
    responseTypeName: "SiteSummary",
  },
  {
    operationId: "listForecastRuns",
    method: "GET",
    path: "/api/v1/forecasts",
    auth: "bearer",
    responseEnvelope: "PaginatedSuccess",
    responseTypeName: "ForecastRunSummary",
  },
  {
    operationId: "createForecastRequest",
    method: "POST",
    path: "/api/v1/forecasts",
    auth: "bearer",
    requestTypeName: "RequestForecastRequest",
    responseEnvelope: "SuccessObject",
    responseTypeName: "ForecastRequestAccepted",
  },
  {
    operationId: "getForecastSummary",
    method: "GET",
    path: "/api/v1/forecasts/{forecastId}/summary",
    auth: "bearer",
    responseEnvelope: "SuccessObject",
    responseTypeName: "ForecastDetailSummary",
  },
  {
    operationId: "getForecastDailyRows",
    method: "GET",
    path: "/api/v1/forecasts/{forecastId}/daily",
    auth: "bearer",
    responseEnvelope: "SuccessArray",
    responseTypeName: "ForecastDailyDetail",
  },
  {
    operationId: "createForecastWhatIf",
    method: "POST",
    path: "/api/v1/forecasts/what-if",
    auth: "bearer",
    requestTypeName: "WhatIfScenarioRequest",
    responseEnvelope: "SuccessObject",
    responseTypeName: "ForecastWhatIfResult",
  },
  {
    operationId: "listDecisions",
    method: "GET",
    path: "/api/v1/decisions",
    auth: "bearer",
    responseEnvelope: "PaginatedSuccess",
    responseTypeName: "DecisionRecord",
  },
  {
    operationId: "getDecision",
    method: "GET",
    path: "/api/v1/decisions/{decisionId}",
    auth: "bearer",
    responseEnvelope: "SuccessObject",
    responseTypeName: "DecisionRecord",
  },
  {
    operationId: "reviewDecision",
    method: "PATCH",
    path: "/api/v1/decisions/{decisionId}/review",
    auth: "bearer",
    requestTypeName: "ReviewDecisionRequest",
    responseEnvelope: "SuccessObject",
    responseTypeName: "DecisionReviewResult",
  },
  {
    operationId: "recordDecisionOutcome",
    method: "POST",
    path: "/api/v1/decisions/{decisionId}/outcome",
    auth: "bearer",
    requestTypeName: "RecordDecisionOutcomeRequest",
    responseEnvelope: "SuccessObject",
    responseTypeName: "DecisionOutcomeResult",
  },
  {
    operationId: "listArbitrageOptions",
    method: "GET",
    path: "/api/v1/arbitrage/{alertId}/options",
    auth: "bearer",
    responseEnvelope: "SuccessObject",
    responseTypeName: "ArbitrageOptionsView",
  },
  {
    operationId: "validateArbitrageDecision",
    method: "POST",
    path: "/api/v1/arbitrage/{alertId}/validate",
    auth: "bearer",
    requestTypeName: "ValidateArbitrageRequest",
    responseEnvelope: "SuccessObject",
    responseTypeName: "ArbitrageValidationResult",
  },
  {
    operationId: "listAlerts",
    method: "GET",
    path: "/api/v1/alerts",
    auth: "bearer",
    responseEnvelope: "SuccessArray",
    responseTypeName: "DashboardAlertRecord",
  },
  {
    operationId: "dismissAlert",
    method: "PATCH",
    path: "/api/v1/alerts/{alertId}/dismiss",
    auth: "bearer",
    responseEnvelope: "SuccessObject",
    responseTypeName: "DashboardAlertRecord",
  },
  {
    operationId: "getAnalyticsCosts",
    method: "GET",
    path: "/api/v1/analytics/costs",
    auth: "bearer",
    responseEnvelope: "SuccessObject",
    responseTypeName: "AnalyticsCostsSummary",
  },
  {
    operationId: "queueExport",
    method: "POST",
    path: "/api/v1/exports/{resource}",
    auth: "bearer",
    requestTypeName: "ExportRequest",
    responseEnvelope: "SuccessObject",
    responseTypeName: "QueuedExportResult",
  },
  {
    operationId: "listDatasets",
    method: "GET",
    path: "/api/v1/datasets",
    auth: "bearer",
    responseEnvelope: "PaginatedSuccess",
    responseTypeName: "DatasetDetailResponse",
  },
  {
    operationId: "getDataset",
    method: "GET",
    path: "/api/v1/datasets/{datasetId}",
    auth: "bearer",
    responseEnvelope: "SuccessObject",
    responseTypeName: "DatasetDetailResponse",
  },
  {
    operationId: "getDatasetRows",
    method: "GET",
    path: "/api/v1/datasets/{datasetId}/data",
    auth: "bearer",
    responseEnvelope: "SuccessObject",
    responseTypeName: "DatasetDataPreviewResponse",
  },
  {
    operationId: "getDatasetColumns",
    method: "GET",
    path: "/api/v1/datasets/{datasetId}/columns",
    auth: "bearer",
    responseEnvelope: "SuccessArray",
    responseTypeName: "GoldSchemaColumn",
  },
  {
    operationId: "getDatasetIngestionLog",
    method: "GET",
    path: "/api/v1/datasets/{datasetId}/ingestion-log",
    auth: "bearer",
    responseEnvelope: "SuccessObject",
    responseTypeName: "IngestionHistoryResponse",
  },
  {
    operationId: "acknowledgeCoverageAlert",
    method: "PATCH",
    path: "/api/v1/coverage-alerts/{alertId}/acknowledge",
    auth: "bearer",
    responseEnvelope: "SuccessObject",
    responseTypeName: "CoverageAlert",
  },
  {
    operationId: "resolveCoverageAlert",
    method: "PATCH",
    path: "/api/v1/coverage-alerts/{alertId}/resolve",
    auth: "bearer",
    responseEnvelope: "SuccessObject",
    responseTypeName: "CoverageAlert",
  },
  {
    operationId: "listOperationalDecisions",
    method: "GET",
    path: "/api/v1/operational-decisions",
    auth: "bearer",
    responseEnvelope: "PaginatedSuccess",
    responseTypeName: "OperationalDecision",
  },
  {
    operationId: "createOperationalDecision",
    method: "POST",
    path: "/api/v1/operational-decisions",
    auth: "bearer",
    requestTypeName: "OperationalDecisionCreateRequest",
    requestBodyRequired: true,
    responseEnvelope: "SuccessObject",
    responseTypeName: "OperationalDecision",
  },
  {
    operationId: "getOperationalDecisionOverrideStats",
    method: "GET",
    path: "/api/v1/operational-decisions/override-stats",
    auth: "bearer",
    responseEnvelope: "SuccessObject",
    responseTypeName: "OverrideStatistics",
  },
  {
    operationId: "listCostParameters",
    method: "GET",
    path: "/api/v1/cost-parameters",
    auth: "bearer",
    responseEnvelope: "SuccessArray",
    responseTypeName: "CostParameterView",
  },
  {
    operationId: "getEffectiveCostParameters",
    method: "GET",
    path: "/api/v1/cost-parameters/effective",
    auth: "bearer",
    responseEnvelope: "SuccessObject",
    responseTypeName: "CostParameterView",
  },
  {
    operationId: "getCostParameterHistory",
    method: "GET",
    path: "/api/v1/cost-parameters/history",
    auth: "bearer",
    responseEnvelope: "SuccessArray",
    responseTypeName: "CostParameterHistoryEntry",
  },
  {
    operationId: "listProofPacks",
    method: "GET",
    path: "/api/v1/proof",
    auth: "bearer",
    responseEnvelope: "SuccessArray",
    responseTypeName: "ProofPack",
  },
  {
    operationId: "getProofSummary",
    method: "GET",
    path: "/api/v1/proof/summary",
    auth: "bearer",
    responseEnvelope: "SuccessObject",
    responseTypeName: "ProofPackSummary",
  },
  {
    operationId: "generateProofPack",
    method: "POST",
    path: "/api/v1/proof/generate",
    auth: "bearer",
    requestTypeName: "ProofPackGenerateRequest",
    responseEnvelope: "SuccessObject",
    responseTypeName: "ProofPack",
  },
  {
    operationId: "getProofPdfUrl",
    method: "GET",
    path: "/api/v1/proof/pdf",
    auth: "bearer",
    responseEnvelope: "SuccessObject",
    responseTypeName: "ProofPdfLink",
  },
] as const satisfies readonly TypedPublicApiOperationContract[];
