import type { ConnectorCatalogItem } from "./types.js";

const OAUTH_CLIENT_HINTS = ["clientId", "clientSecret"] as const;
const API_KEY_HINTS = ["apiKey"] as const;
const SERVICE_ACCOUNT_HINTS = [
  "clientId",
  "clientSecret",
  "clientEmail",
  "privateKey",
] as const;
const SFTP_HINTS = ["host", "username", "password|privateKey"] as const;

export const CONNECTOR_CATALOG: ConnectorCatalogItem[] = [
  {
    vendor: "salesforce",
    label: "Salesforce CRM",
    domain: "crm",
    authModes: ["oauth2", "service_account"],
    sourceObjects: ["Account", "Opportunity", "Case", "Task"],
    recommendedSyncMinutes: 30,
    medallionTargets: ["bronze", "silver", "gold"],
    onboardingModes: ["interactive_oauth", "managed_service_account", "push_api"],
    requiredConfigFields: ["baseUrl"],
    credentialFieldHints: {
      oauth2: OAUTH_CLIENT_HINTS,
      service_account: SERVICE_ACCOUNT_HINTS,
    },
    oauthDefaults: {
      authorizationEndpoint: "https://login.salesforce.com/services/oauth2/authorize",
      tokenEndpoint: "https://login.salesforce.com/services/oauth2/token",
      defaultScopes: ["api", "refresh_token"],
      pkceRequired: true,
    },
  },
  {
    vendor: "ukg",
    label: "UKG Workforce",
    domain: "wfm",
    authModes: ["oauth2", "api_key"],
    sourceObjects: ["Employees", "Schedules", "Timesheets", "Absences"],
    recommendedSyncMinutes: 30,
    medallionTargets: ["bronze", "silver", "gold"],
    onboardingModes: ["credential_submission", "push_api"],
    requiredConfigFields: ["tokenEndpoint", "baseUrl"],
    credentialFieldHints: {
      oauth2: OAUTH_CLIENT_HINTS,
      api_key: API_KEY_HINTS,
    },
  },
  {
    vendor: "toast",
    label: "Toast POS",
    domain: "pos",
    authModes: ["oauth2", "api_key"],
    sourceObjects: ["Orders", "Menus", "Labor", "Inventory"],
    recommendedSyncMinutes: 15,
    medallionTargets: ["bronze", "silver", "gold"],
    onboardingModes: ["credential_submission", "push_api"],
    requiredConfigFields: ["tokenEndpoint", "baseUrl"],
    credentialFieldHints: {
      oauth2: OAUTH_CLIENT_HINTS,
      api_key: API_KEY_HINTS,
    },
  },
  {
    vendor: "olo",
    label: "Olo Ordering",
    domain: "pos",
    authModes: ["api_key"],
    sourceObjects: ["Orders", "Stores", "Products", "Promotions"],
    recommendedSyncMinutes: 15,
    medallionTargets: ["bronze", "silver", "gold"],
    onboardingModes: ["credential_submission", "push_api"],
    requiredConfigFields: ["baseUrl"],
    credentialFieldHints: {
      api_key: API_KEY_HINTS,
    },
  },
  {
    vendor: "cdk",
    label: "CDK Global DMS",
    domain: "dms",
    authModes: ["service_account", "sftp"],
    sourceObjects: ["ServiceOrders", "ROLines", "Vehicle", "Technician"],
    recommendedSyncMinutes: 60,
    medallionTargets: ["bronze", "silver", "gold"],
    onboardingModes: ["managed_service_account", "credential_submission", "push_api"],
    requiredConfigFields: ["baseUrl"],
    credentialFieldHints: {
      service_account: SERVICE_ACCOUNT_HINTS,
      sftp: SFTP_HINTS,
    },
  },
  {
    vendor: "reynolds",
    label: "Reynolds & Reynolds DMS",
    domain: "dms",
    authModes: ["service_account", "sftp"],
    sourceObjects: ["RepairOrder", "Customer", "Vehicle", "Parts"],
    recommendedSyncMinutes: 60,
    medallionTargets: ["bronze", "silver", "gold"],
    onboardingModes: ["managed_service_account", "credential_submission", "push_api"],
    requiredConfigFields: ["baseUrl"],
    credentialFieldHints: {
      service_account: SERVICE_ACCOUNT_HINTS,
      sftp: SFTP_HINTS,
    },
  },
  {
    vendor: "geotab",
    label: "Geotab Telematics",
    domain: "telematics",
    authModes: ["api_key", "oauth2"],
    sourceObjects: ["Trip", "Device", "FaultData", "StatusData"],
    recommendedSyncMinutes: 10,
    medallionTargets: ["bronze", "silver", "gold"],
    onboardingModes: ["credential_submission", "push_api"],
    requiredConfigFields: ["baseUrl"],
    credentialFieldHints: {
      oauth2: OAUTH_CLIENT_HINTS,
      api_key: API_KEY_HINTS,
    },
  },
  {
    vendor: "fourth",
    label: "Fourth Hospitality WFM",
    domain: "wfm",
    authModes: ["api_key", "sftp"],
    sourceObjects: ["Employees", "Roster", "Timeclock", "LaborForecast"],
    recommendedSyncMinutes: 30,
    medallionTargets: ["bronze", "silver", "gold"],
    onboardingModes: ["credential_submission", "push_api"],
    requiredConfigFields: ["baseUrl"],
    credentialFieldHints: {
      api_key: API_KEY_HINTS,
      sftp: SFTP_HINTS,
    },
  },
  {
    vendor: "oracle_tm",
    label: "Oracle Transportation Management",
    domain: "tms",
    authModes: ["oauth2", "service_account"],
    sourceObjects: ["Shipment", "OrderRelease", "Route", "Stop"],
    recommendedSyncMinutes: 30,
    medallionTargets: ["bronze", "silver", "gold"],
    onboardingModes: ["credential_submission", "managed_service_account", "push_api"],
    requiredConfigFields: ["tokenEndpoint", "baseUrl"],
    credentialFieldHints: {
      oauth2: OAUTH_CLIENT_HINTS,
      service_account: SERVICE_ACCOUNT_HINTS,
    },
  },
  {
    vendor: "sap_tm",
    label: "SAP Transportation Management",
    domain: "tms",
    authModes: ["oauth2", "service_account"],
    sourceObjects: ["FreightOrder", "FreightUnit", "Resource", "Stop"],
    recommendedSyncMinutes: 30,
    medallionTargets: ["bronze", "silver", "gold"],
    onboardingModes: ["credential_submission", "managed_service_account", "push_api"],
    requiredConfigFields: ["tokenEndpoint", "baseUrl"],
    credentialFieldHints: {
      oauth2: OAUTH_CLIENT_HINTS,
      service_account: SERVICE_ACCOUNT_HINTS,
    },
  },
  {
    vendor: "blue_yonder",
    label: "Blue Yonder Planning",
    domain: "planning",
    authModes: ["api_key", "service_account"],
    sourceObjects: ["DemandPlan", "LaborPlan", "Store", "SKU"],
    recommendedSyncMinutes: 60,
    medallionTargets: ["bronze", "silver", "gold"],
    onboardingModes: ["credential_submission", "managed_service_account", "push_api"],
    requiredConfigFields: ["baseUrl"],
    credentialFieldHints: {
      api_key: API_KEY_HINTS,
      service_account: SERVICE_ACCOUNT_HINTS,
    },
  },
  {
    vendor: "manhattan",
    label: "Manhattan Associates",
    domain: "planning",
    authModes: ["api_key", "service_account"],
    sourceObjects: ["Wave", "Task", "Inventory", "Shipment"],
    recommendedSyncMinutes: 30,
    medallionTargets: ["bronze", "silver", "gold"],
    onboardingModes: ["credential_submission", "managed_service_account", "push_api"],
    requiredConfigFields: ["baseUrl"],
    credentialFieldHints: {
      api_key: API_KEY_HINTS,
      service_account: SERVICE_ACCOUNT_HINTS,
    },
  },
  {
    vendor: "ncr_aloha",
    label: "NCR Aloha POS",
    domain: "pos",
    authModes: ["api_key", "sftp"],
    sourceObjects: ["Check", "Item", "Labor", "Inventory"],
    recommendedSyncMinutes: 15,
    medallionTargets: ["bronze", "silver", "gold"],
    onboardingModes: ["credential_submission", "push_api"],
    requiredConfigFields: ["baseUrl"],
    credentialFieldHints: {
      api_key: API_KEY_HINTS,
      sftp: SFTP_HINTS,
    },
  },
];
