import type { ConnectorCatalogItem } from "./types.js";

export const CONNECTOR_CATALOG: ConnectorCatalogItem[] = [
  {
    vendor: "salesforce",
    label: "Salesforce CRM",
    domain: "crm",
    authModes: ["oauth2", "service_account"],
    sourceObjects: ["Account", "Opportunity", "Case", "Task"],
    recommendedSyncMinutes: 30,
    medallionTargets: ["bronze", "silver", "gold"],
  },
  {
    vendor: "ukg",
    label: "UKG Workforce",
    domain: "wfm",
    authModes: ["oauth2", "api_key"],
    sourceObjects: ["Employees", "Schedules", "Timesheets", "Absences"],
    recommendedSyncMinutes: 30,
    medallionTargets: ["bronze", "silver", "gold"],
  },
  {
    vendor: "toast",
    label: "Toast POS",
    domain: "pos",
    authModes: ["oauth2", "api_key"],
    sourceObjects: ["Orders", "Menus", "Labor", "Inventory"],
    recommendedSyncMinutes: 15,
    medallionTargets: ["bronze", "silver", "gold"],
  },
  {
    vendor: "olo",
    label: "Olo Ordering",
    domain: "pos",
    authModes: ["api_key"],
    sourceObjects: ["Orders", "Stores", "Products", "Promotions"],
    recommendedSyncMinutes: 15,
    medallionTargets: ["bronze", "silver", "gold"],
  },
  {
    vendor: "cdk",
    label: "CDK Global DMS",
    domain: "dms",
    authModes: ["service_account", "sftp"],
    sourceObjects: ["ServiceOrders", "ROLines", "Vehicle", "Technician"],
    recommendedSyncMinutes: 60,
    medallionTargets: ["bronze", "silver", "gold"],
  },
  {
    vendor: "reynolds",
    label: "Reynolds & Reynolds DMS",
    domain: "dms",
    authModes: ["service_account", "sftp"],
    sourceObjects: ["RepairOrder", "Customer", "Vehicle", "Parts"],
    recommendedSyncMinutes: 60,
    medallionTargets: ["bronze", "silver", "gold"],
  },
  {
    vendor: "geotab",
    label: "Geotab Telematics",
    domain: "telematics",
    authModes: ["api_key", "oauth2"],
    sourceObjects: ["Trip", "Device", "FaultData", "StatusData"],
    recommendedSyncMinutes: 10,
    medallionTargets: ["bronze", "silver", "gold"],
  },
  {
    vendor: "fourth",
    label: "Fourth Hospitality WFM",
    domain: "wfm",
    authModes: ["api_key", "sftp"],
    sourceObjects: ["Employees", "Roster", "Timeclock", "LaborForecast"],
    recommendedSyncMinutes: 30,
    medallionTargets: ["bronze", "silver", "gold"],
  },
  {
    vendor: "oracle_tm",
    label: "Oracle Transportation Management",
    domain: "tms",
    authModes: ["oauth2", "service_account"],
    sourceObjects: ["Shipment", "OrderRelease", "Route", "Stop"],
    recommendedSyncMinutes: 30,
    medallionTargets: ["bronze", "silver", "gold"],
  },
  {
    vendor: "sap_tm",
    label: "SAP Transportation Management",
    domain: "tms",
    authModes: ["oauth2", "service_account"],
    sourceObjects: ["FreightOrder", "FreightUnit", "Resource", "Stop"],
    recommendedSyncMinutes: 30,
    medallionTargets: ["bronze", "silver", "gold"],
  },
  {
    vendor: "blue_yonder",
    label: "Blue Yonder Planning",
    domain: "planning",
    authModes: ["api_key", "service_account"],
    sourceObjects: ["DemandPlan", "LaborPlan", "Store", "SKU"],
    recommendedSyncMinutes: 60,
    medallionTargets: ["bronze", "silver", "gold"],
  },
  {
    vendor: "manhattan",
    label: "Manhattan Associates",
    domain: "planning",
    authModes: ["api_key", "service_account"],
    sourceObjects: ["Wave", "Task", "Inventory", "Shipment"],
    recommendedSyncMinutes: 30,
    medallionTargets: ["bronze", "silver", "gold"],
  },
  {
    vendor: "ncr_aloha",
    label: "NCR Aloha POS",
    domain: "pos",
    authModes: ["api_key", "sftp"],
    sourceObjects: ["Check", "Item", "Labor", "Inventory"],
    recommendedSyncMinutes: 15,
    medallionTargets: ["bronze", "silver", "gold"],
  },
];
