from typing import overload

class YAMLError(Exception): ...

class YAMLValidationError(YAMLError): ...

class Validator:
    def __or__(self, other: Validator) -> Validator: ...

class Bool(Validator):
    def __init__(self) -> None: ...

class Int(Validator):
    def __init__(self) -> None: ...

class Str(Validator):
    def __init__(self) -> None: ...

class Enum(Validator):
    def __init__(self, items: list[str]) -> None: ...

class Seq(Validator):
    def __init__(self, validator: Validator) -> None: ...

class Map(Validator):
    def __init__(self, mapping: dict[object, Validator]) -> None: ...

class MapPattern(Validator):
    def __init__(self, key_validator: Validator, value_validator: Validator) -> None: ...

class Optional:
    def __init__(self, key: str, default: str | None = ...) -> None: ...

class YAML:
    data: object

@overload
def load(yaml_string: str, schema: Validator) -> YAML: ...
@overload
def load(yaml_string: str, schema: None = ...) -> YAML: ...
