import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";

const repoRoot = process.cwd();
const defaultModelDir = path.join(repoRoot, "app-api/app/models");
const defaultOutputPath = path.join(
  repoRoot,
  "docs/cto/visuals/schema-public-auto-generated.mmd",
);

function listFiles(dirPath) {
  return readdirSync(dirPath)
    .filter((entry) => statSync(path.join(dirPath, entry)).isFile())
    .filter((entry) => entry.endsWith(".py") && entry !== "__init__.py")
    .sort();
}

export function collectSqlAlchemyGraph(dirPath = defaultModelDir) {
  const tables = new Set();
  const relations = new Set();

  for (const entry of listFiles(dirPath)) {
    const fullPath = path.join(dirPath, entry);
    const source = readFileSync(fullPath, "utf8");
    const localTables = [...source.matchAll(/__tablename__\s*=\s*["']([^"']+)["']/g)].map(
      (match) => match[1],
    );

    for (const tableName of localTables) {
      tables.add(tableName);
    }

    const foreignKeys = [...source.matchAll(/ForeignKey\("([^".]+)\.([^"]+)"(?:,|\))/g)];
    const ownerTable = localTables[0];
    if (!ownerTable) {
      continue;
    }

    for (const match of foreignKeys) {
      const targetTable = match[1];
      relations.add(`${ownerTable}::${targetTable}`);
      tables.add(targetTable);
    }
  }

  return {
    tables: [...tables].sort(),
    relations: [...relations]
      .map((relation) => {
        const [from, to] = relation.split("::");
        return { from, to };
      })
      .sort((left, right) => {
        if (left.from === right.from) {
          return left.to.localeCompare(right.to);
        }
        return left.from.localeCompare(right.from);
      }),
  };
}

export function renderMermaidErd(graph) {
  const lines = [
    "%% Auto-generated by scripts/generate-cto-erd.mjs",
    "%% Source: app-api/app/models/*",
    "erDiagram",
  ];

  for (const tableName of graph.tables) {
    lines.push(`    ${toMermaidEntity(tableName)} {`);
    lines.push("        string id");
    lines.push("    }");
  }

  if (graph.tables.length > 0) {
    lines.push("");
  }

  for (const relation of graph.relations) {
    lines.push(
      `    ${toMermaidEntity(relation.to)} ||--o{ ${toMermaidEntity(relation.from)} : "references"`,
    );
  }

  return `${lines.join("\n")}\n`;
}

function toMermaidEntity(tableName) {
  return tableName.replace(/[^A-Za-z0-9_]/g, "_");
}

function parseArgs(argv) {
  const options = {
    modelDir: defaultModelDir,
    outputPath: defaultOutputPath,
    stdout: false,
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];

    if (arg === "--stdout") {
      options.stdout = true;
      continue;
    }

    if (arg === "--models") {
      const next = argv[index + 1];
      if (!next) {
        throw new Error("--models requires a path");
      }
      options.modelDir = path.resolve(next);
      index += 1;
      continue;
    }

    if (arg === "--out") {
      const next = argv[index + 1];
      if (!next) {
        throw new Error("--out requires a path");
      }
      options.outputPath = path.resolve(next);
      index += 1;
    }
  }

  return options;
}

export function runCli(argv = process.argv.slice(2)) {
  const options = parseArgs(argv);
  const graph = collectSqlAlchemyGraph(options.modelDir);
  const mermaid = renderMermaidErd(graph);

  if (options.stdout) {
    process.stdout.write(mermaid);
    return 0;
  }

  mkdirSync(path.dirname(options.outputPath), { recursive: true });
  writeFileSync(options.outputPath, mermaid, "utf8");
  console.log(
    `[generate-cto-erd] OK: ${graph.tables.length} tables, ${graph.relations.length} relations -> ${path.relative(repoRoot, options.outputPath)}`,
  );
  return 0;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  process.exitCode = runCli();
}
