import type { SerpPageBrief } from "./serp-briefs-fr.types";

export const serpBriefsTail: Record<string, SerpPageBrief> = {
  "cout-sous-couverture": {
    outlineH2: [
      "Perimetre de calcul multi-sites",
      "Couts directs de l'urgence",
      "Couts indirects et caches",
      "Methode de consolidation DAF",
      "Calculateur cout de l'inaction",
      "Cas chiffre avec hypotheses",
    ],
    paa: [
      "Comment calculer le cout de sous-couverture ?",
      "Quels couts caches inclure ?",
      "Comment consolider multi-sites ?",
      "Quel KPI suivre ?",
      "Comment utiliser ce cout pour arbitrer ?",
    ],
    backlinks: [
      "Publier calculateur et fiche methode CFO",
      "PR avec chiffres de cout d'inaction",
      "Relais communautes finance operationnelle",
    ],
  },
  "cout-sous-effectif": {
    outlineH2: [
      "Sous-effectif vs sous-couverture",
      "Couts directs a comptabiliser",
      "Couts indirects et degradation",
      "Methode de calcul en 7 etapes",
      "Erreurs de calcul frequentes",
      "Template de chiffrage",
    ],
    paa: [
      "Comment chiffrer un sous-effectif ?",
      "Difference avec sous-couverture ?",
      "Quels couts indirects integrer ?",
      "Comment eviter les biais ?",
      "Quel plan d'action prioriser ?",
    ],
    backlinks: [
      "Template tableau de couts publie en libre acces",
      "Guest content DAF x Ops",
      "Diffusion via bibliotheques formation supply",
    ],
  },
  "cout-interim-urgence": {
    outlineH2: [
      "Composants du cout interim urgence",
      "Pourquoi l'urgence surcoute",
      "Comparatif urgence vs anticipe",
      "Scenarios interim vs HS vs reallocation",
      "Reduire le recours urgence",
      "Simulateur comparatif",
    ],
    paa: [
      "Pourquoi l'interim d'urgence coute plus cher ?",
      "Comment le chiffrer correctement ?",
      "Comment comparer a HS ?",
      "Quelle strategie d'anticipation ?",
      "Quel ROI attendre ?",
    ],
    backlinks: [
      "Etude comparative urgence vs anticipe",
      "Co-contenu avec experts staffing",
      "Interventions conferences supply",
    ],
  },
  "cout-heures-supplementaires": {
    outlineH2: [
      "Composants du cout total HS",
      "Calcul pas a pas avec exemple",
      "Couts indirects fatigue/qualite",
      "Quand les HS sont rationnelles",
      "Comparatif HS vs interim",
      "Calculateur HS",
    ],
    paa: [
      "Comment calculer le cout d'une heure sup ?",
      "HS moins cheres que l'interim ?",
      "Quels effets indirects inclure ?",
      "Quelles contraintes de pilotage ?",
      "Comment decider rapidement ?",
    ],
    backlinks: [
      "Publier calculateur HS tout compris",
      "Citations dans contenus RH operations",
      "Co-publication avec cabinets performance",
    ],
  },
  "arbitrage-interim-vs-heures-supp": {
    outlineH2: [
      "Entrees de decision criticite/horizon",
      "Calcul cout total des options",
      "Risques qualite et securite",
      "Arbre de decision visuel",
      "Trois scenarios d'exemple",
      "Template comparaison",
    ],
    paa: [
      "Interim ou HS: que choisir ?",
      "Comment integrer la criticite ?",
      "Comment comparer des couts incomplets ?",
      "Quel impact qualite/sante ?",
      "Que faire si aucune option n'est ideale ?",
    ],
    backlinks: [
      "Publier arbre de decision partageable",
      "Webinar Ops/DAF sur arbitrage sous tension",
      "Co-contenu avec ecosysteme planning",
    ],
  },
  "cout-absenteisme-entrepot": {
    outlineH2: [
      "Typologies d'absence a suivre",
      "Couts directs de remplacement",
      "Couts indirects operationnels",
      "Prevision impact court horizon",
      "Plan d'action terrain",
      "Template cout + score risque",
    ],
    paa: [
      "Comment calculer le cout de l'absenteisme ?",
      "Quels KPI suivre ?",
      "Comment anticiper les pics d'absence ?",
      "Comment agir sans degrader le climat ?",
      "Quels leviers sont efficaces en logistique ?",
    ],
    backlinks: [
      "Publier template cout absentéisme",
      "Partenariat cabinets QVT et operations",
      "Interventions RH Ops sur approche cout",
    ],
  },
  "cout-turnover-logistique": {
    outlineH2: [
      "Definition et metriques de turnover",
      "Couts directs recrutement/onboarding",
      "Couts indirects productivite/qualite",
      "Drivers terrain dominants",
      "Lien turnover et sous-couverture",
      "Calculateur turnover",
    ],
    paa: [
      "Quel est le cout d'un depart ?",
      "Comment calculer le turnover ?",
      "Quels drivers en logistique ?",
      "Comment reduire durablement ?",
      "Comment mesurer avant/apres ?",
    ],
    backlinks: [
      "Publier calculateur + benchmark par fourchettes",
      "Co-contenu medias RH/logistique",
      "Etudes de cas anonymisees",
    ],
  },
  "pilotage-masse-salariale-logistique": {
    outlineH2: [
      "KPI coeur couverture/cout/service",
      "Consolidation multi-sites pragmatique",
      "Arbitrage cout inaction vs options",
      "Rituels hebdo et mensuels",
      "Decision log et preuve d'impact",
      "Template revue masse salariale",
    ],
    paa: [
      "Comment piloter masse salariale sans casser le service ?",
      "Quels KPI presenter au comite ?",
      "Comment consolider multi-sites ?",
      "Comment chiffrer l'inaction ?",
      "Comment prouver le ROI ?",
    ],
    backlinks: [
      "Publier template revue Ops/DAF",
      "Webinar CFO/COO",
      "Guest content controle de gestion operationnel",
    ],
  },
  "cout-inaction-logistique": {
    outlineH2: [
      "Definir l'inaction par type de risque",
      "Construire une baseline robuste",
      "Lister les couts disperses",
      "Relier cout et decisions",
      "Exemple chiffre multi-sites",
      "Calculateur cout inaction",
    ],
    paa: [
      "C'est quoi le cout de l'inaction ?",
      "Comment le mesurer sans data parfaite ?",
      "Comment consolider multi-sites ?",
      "Comment l'utiliser en budget ?",
      "Comment le defendre au CODIR ?",
    ],
    backlinks: [
      "PR sur cout invisible en logistique",
      "Co-etude avec cabinet ou ecole",
      "Relais medias finance et operations",
    ],
  },
  "playbook-actions-sous-effectif": {
    outlineH2: [
      "Categories d'actions prioritaires",
      "Conditions de reussite par action",
      "Matrice impact/effort",
      "Checklists d'execution",
      "Usage en revue hebdomadaire",
      "Pack playbook telechargeable",
    ],
    paa: [
      "Quelles actions en cas de sous-effectif ?",
      "Comment prioriser rapidement ?",
      "Quelles actions evitent l'urgence ?",
      "Quelles actions coutent le moins ?",
      "Comment standardiser la decision ?",
    ],
    backlinks: [
      "Publier pack playbook PDF + templates",
      "Co-signature avec experts terrain",
      "Diffusion communautes managers logistique",
    ],
  },
  "traceabilite-decisions-operationnelles": {
    outlineH2: [
      "Pourquoi la tracabilite echoue souvent",
      "Champs indispensables du decision log",
      "Roles et validation",
      "Lien decisions, couts et KPI",
      "Exemple complet fictif",
      "Template Notion/Sheets",
    ],
    paa: [
      "C'est quoi un decision log ?",
      "Quels champs faut-il inclure ?",
      "Comment eviter la bureaucratie ?",
      "Comment l'utiliser avec le DAF ?",
      "Comment relier decision et ROI ?",
    ],
    backlinks: [
      "Publier template decision log auditable",
      "Guest posts gouvernance operations",
      "Partenariats ecoles management operationnel",
    ],
  },
  "mesure-avant-apres-performance": {
    outlineH2: [
      "Biais classiques de mesure",
      "Choix de baseline et granularite",
      "KPI cout/service/qualite",
      "Methodes simples attribution impact",
      "Lien avec decision log",
      "Template de mesure avant/apres",
    ],
    paa: [
      "Comment mesurer un ROI operationnel ?",
      "Comment eviter les biais saisonniers ?",
      "Quels KPI privilegier ?",
      "Comment attribuer l'impact ?",
      "Comment presenter au CODIR ?",
    ],
    backlinks: [
      "Publier toolkit avant/apres complet",
      "Co-publication avec cabinets data/ops",
      "Relais medias performance industrielle",
    ],
  },
  "logiciel-planification-personnel-logistique": {
    outlineH2: [
      "Besoins metier logistiques",
      "Categories d'outils a comparer",
      "Checklist d'achat exhaustive",
      "Grille de scoring telechargeable",
      "Pieges de selection frequents",
      "Quand ajouter une couche decisionnelle",
    ],
    paa: [
      "Quel logiciel choisir en logistique ?",
      "WFM ou outil planning ?",
      "Quelles fonctionnalites sont indispensables ?",
      "Comment comparer sans se tromper ?",
      "Comment prouver le ROI outil ?",
    ],
    backlinks: [
      "Publier grille scoring open access",
      "Comparatifs de categories neutres",
      "Webinars choix outillage avec integrateurs",
    ],
  },
  "wfm-logistique": {
    outlineH2: [
      "Definition et perimetre WFM",
      "Fonctionnalites standard du WFM",
      "Limites frequentes pour arbitrage cout",
      "Stack cible WFM + BI + decision",
      "Checklist adequation au contexte",
      "Cas types d'usage entreprise",
    ],
    paa: [
      "C'est quoi un WFM ?",
      "Difference WFM et planning ?",
      "Le WFM anticipe-t-il la sous-couverture ?",
      "Comment prouver ROI WFM ?",
      "Quel stack cible en pratique ?",
    ],
    backlinks: [
      "Publier matrice categorie WFM vs decision",
      "Co-contenu avec integrateurs WFM",
      "Relais contenus architecture SI ops",
    ],
  },
  "taux-de-service-logistique": {
    outlineH2: [
      "Definitions OTIF et variantes",
      "Calcul pas a pas du taux service",
      "Pieges de perimetre et exceptions",
      "Lien taux service et staffing",
      "Arbitrage service vs cout",
      "Template KPI et cas pratique",
    ],
    paa: [
      "Comment calculer un taux de service ?",
      "OTIF vs taux de service: difference ?",
      "Pourquoi le taux se degrade ?",
      "Comment le relier au staffing ?",
      "Comment arbitrer cout vs service ?",
    ],
    backlinks: [
      "Publier template KPI service en libre acces",
      "Co-contenu medias supply chain",
      "Partenariat cabinets SLA et penalites",
    ],
  },
};
