import type { SerpPageBrief } from "./serp-briefs-fr.types";

export const serpBriefsCore: Record<string, SerpPageBrief> = {
  "sous-couverture-definition": {
    outlineH2: [
      "Definition simple capacite vs charge",
      "Signaux faibles avant rupture",
      "Causes racines frequentes",
      "Couts directs et indirects",
      "Mesure pratique par KPI",
      "Playbook de reduction du risque",
    ],
    paa: [
      "C'est quoi la sous-couverture ?",
      "Comment mesurer un trou de couverture ?",
      "Quelles causes reviennent le plus ?",
      "Quel est le cout reel ?",
      "Comment anticiper a J+7 ?",
    ],
    backlinks: [
      "Publier un glossaire visuel capacite vs charge reutilisable",
      "Co-publier un diagnostic type avec cabinet ops",
      "Intervenir en webinar Ops x Finance avec ressource liee",
    ],
  },
  "sous-couverture-logistique": {
    outlineH2: [
      "Specificites logistiques du risque de couverture",
      "Top causes en entrepot et transport",
      "Early-warning court horizon J+3 a J+14",
      "Scenarios d'action et couts associes",
      "KPI service et staffing relies",
      "Cas chiffre avant/apres",
    ],
    paa: [
      "Comment anticiper un sous-effectif logistique ?",
      "Quels KPI signalent une rupture imminente ?",
      "Comment arbitrer interim vs HS ?",
      "Comment eviter les decisions de derniere minute ?",
      "Comment prouver le ROI des actions ?",
    ],
    backlinks: [
      "Diffuser un cas d'usage pic activite en PDF",
      "Co-marketing avec integrateurs WMS/ERP",
      "Podcast supply avec page recap sur le site",
    ],
  },
  "trous-de-couverture-planning": {
    outlineH2: [
      "Trou ponctuel vs sous-couverture structurelle",
      "Checklist detection hebdomadaire",
      "Matrice de criticite operationnelle",
      "Options rapides et cout unitaire",
      "Rituel de revue glissante",
      "Template de pilotage telechargeable",
    ],
    paa: [
      "C'est quoi un trou de couverture ?",
      "Comment le detecter en avance ?",
      "Quelles donnees minimales utiliser ?",
      "Quelles actions lancer en premier ?",
      "Comment prioriser sous contrainte ?",
    ],
    backlinks: [
      "Publier un template revue hebdo gratuit",
      "Guest post categorie planning vs decision",
      "Partenariat ecoles logistiques pour usage pedagogique",
    ],
  },
  "ecart-capacite-charge": {
    outlineH2: [
      "Modele minimal capacite/charge",
      "Capacite theorique vs capacite utile",
      "Charge prevue vs charge reelle",
      "Buffers de variabilite",
      "Erreurs de calcul frequentes",
      "Exemple chiffre complet",
    ],
    paa: [
      "Comment calculer la capacite d'un site ?",
      "Comment estimer la charge reelle ?",
      "Quels temps standards utiliser ?",
      "Quel buffer prevoir ?",
      "Comment integrer l'absenteisme ?",
    ],
    backlinks: [
      "Publier modele Sheets + dataset fictif",
      "Co-signer la methodologie avec cabinet operations",
      "Promouvoir via contenus productivite industrielle",
    ],
  },
  "taux-de-couverture-planning": {
    outlineH2: [
      "Formules de taux de couverture",
      "Seuil critique par activite",
      "Couverture globale vs couverture critique",
      "Visualisations utiles pour comite",
      "Lien couverture et cout d'inaction",
      "Template KPI de suivi",
    ],
    paa: [
      "Quel est un bon taux de couverture ?",
      "Comment definir un seuil critique ?",
      "Pourquoi la couverture globale trompe ?",
      "Comment suivre par competence ?",
      "Comment relier au cout ?",
    ],
    backlinks: [
      "Publier mini-guide seuil de couverture",
      "Partage via associations metier logistique",
      "Co-contenu avec ecosysteme WFM/export",
    ],
  },
  "early-warning-sous-effectif": {
    outlineH2: [
      "Pourquoi les alertes echouent souvent",
      "Horizon J+3 vs J+7 vs J+14",
      "Facteurs explicatifs non boite noire",
      "Rituel de revue Ops/Finance",
      "Minimum viable data pour demarrer",
      "Exemple carte de risque",
    ],
    paa: [
      "Comment anticiper un sous-effectif a une semaine ?",
      "Quelles donnees faut-il ?",
      "Comment limiter les fausses alertes ?",
      "Qui doit piloter l'early-warning ?",
      "Comment relier alerte et decision ?",
    ],
    backlinks: [
      "Publier guide de gouvernance early-warning",
      "Webinar operations multi-sites avec replay",
      "Etude cout des decisions jour J",
    ],
  },
  "anticiper-sous-effectif-entrepot": {
    outlineH2: [
      "Top signaux faibles a surveiller",
      "Score de tension terrain",
      "Actions immediates 24-72h",
      "Actions court terme S+1/S+2",
      "Actions structurelles long terme",
      "Template score telechargeable",
    ],
    paa: [
      "Quels indicateurs annoncent le sous-effectif ?",
      "Comment prioriser les actions ?",
      "Quels leviers coutent le moins cher ?",
      "Comment eviter l'epuisement des equipes ?",
      "Comment objectiver au CODIR ?",
    ],
    backlinks: [
      "Publier score tension reutilisable",
      "Co-edition avec ecole logistique",
      "Tribune medias sur signaux faibles",
    ],
  },
  "carte-des-risques-sous-couverture": {
    outlineH2: [
      "Structure du livrable de risque",
      "Scoring criticite impact x cout",
      "Facteurs explicatifs a tracer",
      "Options d'action comparees",
      "Animation de la revue hebdo",
      "Modele de carte telechargeable",
    ],
    paa: [
      "A quoi sert une carte des risques ?",
      "Comment scorer la criticite ?",
      "Comment expliquer un risque ?",
      "Quels champs inclure ?",
      "Comment l'utiliser en comite ?",
    ],
    backlinks: [
      "Diffuser modele carte en open resource",
      "Co-creation avec integrateurs SI ops",
      "Presentation meetup sur revue de risques",
    ],
  },
  "planification-effectifs-logistique": {
    outlineH2: [
      "Niveaux de maturite planification",
      "Donnees minimales puis avancees",
      "Methodes de calcul et scenarios",
      "Contraintes competences et conformite",
      "Gouvernance multi-sites",
      "Checklist revue planning efficace",
    ],
    paa: [
      "Quelles donnees faut-il pour planifier ?",
      "Comment gerer les pics ?",
      "Comment integrer les competences ?",
      "Comment aligner Ops et Finance ?",
      "Quelle difference avec un outil planning ?",
    ],
    backlinks: [
      "Publier maturity model visuel",
      "Webinars avec cabinets transformation",
      "Guide achat outillage avec framework cite",
    ],
  },
  "dimensionnement-effectifs-entrepot": {
    outlineH2: [
      "Decoupage par activite",
      "Construction de temps standards",
      "Conversion en heures utiles et FTE",
      "Buffers de variabilite et absence",
      "Exemple chiffre complet",
      "Simulateur et export",
    ],
    paa: [
      "Comment dimensionner un entrepot ?",
      "Comment calculer les FTE necessaires ?",
      "Quel taux d'absence integrer ?",
      "Quels buffers prevoir ?",
      "Comment tester des scenarios ?",
    ],
    backlinks: [
      "Mettre a disposition simulateur gratuit",
      "Co-publication methodologique avec cabinet IE",
      "Referencement dans ressources de formation",
    ],
  },
  "calcul-besoin-effectifs-entrepot": {
    outlineH2: [
      "Inputs du calculateur FTE",
      "Resultats et lecture de risque",
      "Interpretation des deficits",
      "Scenarios comparatifs d'action",
      "Export et partage comite",
      "Limites du modele",
    ],
    paa: [
      "Comment calculer le besoin en effectifs ?",
      "Quelle difference heures vs FTE ?",
      "Comment integrer les absences ?",
      "Quel buffer utiliser ?",
      "Comment passer du calcul a l'action ?",
    ],
    backlinks: [
      "Diffuser outil calculateur dans communautes ops",
      "Partenariats ecoles pour usage pedagogique",
      "Mentions dans contenus dimensionnement",
    ],
  },
  "prevision-charge-travail-entrepot": {
    outlineH2: [
      "Donnees necessaires pour prevoir",
      "Methodes simples vs avancees",
      "Detection des pics et anomalies",
      "Conversion prevision vers staffing",
      "Lien prevision et carte de risque",
      "Dataset exemple telechargeable",
    ],
    paa: [
      "Comment prevoir une charge logistique ?",
      "Comment gerer la saisonnalite ?",
      "Comment prevoir les pics ?",
      "Quelle granularite choisir ?",
      "Comment convertir en effectifs ?",
    ],
    backlinks: [
      "Publier dataset fictif et notebook",
      "Co-article avec ecosysteme BI/forecasting",
      "Intervention conference supply avec support",
    ],
  },
  "capacity-planning-logistique": {
    outlineH2: [
      "Definitions communes capacite/charge/SLA",
      "Horizon hebdo et mensuel",
      "Rituels de pilotage",
      "Scenarios et arbitrage economique",
      "Preuve d'impact et decision log",
      "Template revue capacite",
    ],
    paa: [
      "C'est quoi le capacity planning ?",
      "Difference avec planning operationnel ?",
      "Quel horizon choisir ?",
      "Comment chiffrer des scenarios ?",
      "Comment prouver l'impact ?",
    ],
    backlinks: [
      "Positionner la page en guide de reference FR",
      "Co-publication Ops + Finance",
      "Relais medias pilotage capacite",
    ],
  },
  "workforce-planning-multi-sites": {
    outlineH2: [
      "Ce qui doit etre centralise ou local",
      "KPI communs multi-sites",
      "Regles de reallocation inter-sites",
      "Rituels COO/DAF",
      "Architecture data minimale",
      "Modele RACI de gouvernance",
    ],
    paa: [
      "Comment piloter des equipes multi-sites ?",
      "Faut-il centraliser le planning ?",
      "Comment eviter les conflits entre sites ?",
      "Comment arbitrer avec le DAF ?",
      "Comment mesurer l'impact ?",
    ],
    backlinks: [
      "Publier playbook et RACI multi-sites",
      "Partenariat cabinets transformation reseau",
      "Conference Ops multi-sites avec ressources",
    ],
  },
  "reallocation-inter-sites-effectifs": {
    outlineH2: [
      "Quand reallouer est pertinent",
      "Modele de cout de reallocation",
      "Contraintes competences et qualite",
      "Impact SLA et penalites",
      "Checklist de decision rapide",
      "Exemple d'arbitrage chiffre",
    ],
    paa: [
      "Quand reallouer est une bonne idee ?",
      "Comment chiffrer une reallocation ?",
      "Quels risques qualite/service ?",
      "Comment comparer a interim/HS ?",
      "Comment expliquer la decision au comite ?",
    ],
    backlinks: [
      "Publier matrice de decision visuelle",
      "Co-contenu avec cabinets transport",
      "Etudes de cas anonymisees avant/apres",
    ],
  },
};
